/**
 * A QR code, encoded here rather than fetched.
 *
 * The one place Tally needs one is the invite QR a core member holds up to the
 * volunteer standing beside them (see `docs/team-access.md`, P2). That is a
 * ten-second act on a screen that already has the token in memory, and every
 * way of not writing this was worse: a CDN script is refused by the content
 * security policy and would put the invitation URL — a single-use grant to a
 * roster of minors — through somebody else's server; a rendering API is the
 * same leak with a round trip; and a dependency is ~15KB carried by every
 * person who never presses QR. This is ~6KB, behind `await import()`, and the
 * bytes only ever load on the press.
 *
 * Deliberately narrow. Byte mode only, error correction level M, versions 1
 * through 10 — 213 bytes, which is four times the longest join URL a
 * deployment can produce. Anything outside that throws rather than guessing,
 * because a QR that encodes the wrong thing is indistinguishable from one that
 * encodes the right thing until somebody points a phone at it.
 *
 * Every step below is ISO/IEC 18004 as it is normally implemented. The reason
 * to trust it is not the comments: `qr.test.ts` compares whole matrices
 * against fixtures generated by an unrelated encoder, so a table typed one
 * digit out fails the suite rather than shipping a square that will not scan.
 */

/**
 * The largest version this encodes, and why it stops there.
 *
 * A join URL is an origin plus `/join/` plus a 22-character token — 60-odd
 * bytes on a real deployment, which is a version 4 or 5 symbol. Version 10
 * holds 213 bytes at level M, so the ceiling is generous; going further would
 * mean carrying the whole 40-version block table for a case nobody has, and a
 * bigger symbol is a *worse* QR in the room anyway — the same phone camera has
 * to resolve more modules across the same screen.
 */
const MAX_VERSION = 10;

/**
 * How many data codewords each version holds, and how they are grouped.
 *
 * One row per version, level M only. `blocks` is the pairs the spec's table
 * gives — `[how many blocks, data codewords in each]` — because from version 8
 * up a symbol is split into two groups whose blocks differ by exactly one
 * codeword, and the interleave below has to know which is which.
 */
interface VersionSpec {
  /** Error-correction codewords per block. Every block in a version has the same count. */
  ecPerBlock: number;
  blocks: readonly (readonly [blocks: number, dataCodewords: number])[];
}

const VERSIONS: Readonly<Record<number, VersionSpec>> = {
  1: { ecPerBlock: 10, blocks: [[1, 16]] },
  2: { ecPerBlock: 16, blocks: [[1, 28]] },
  3: { ecPerBlock: 26, blocks: [[1, 44]] },
  4: { ecPerBlock: 18, blocks: [[2, 32]] },
  5: { ecPerBlock: 24, blocks: [[2, 43]] },
  6: { ecPerBlock: 16, blocks: [[4, 27]] },
  7: { ecPerBlock: 18, blocks: [[4, 31]] },
  8: { ecPerBlock: 22, blocks: [[2, 38], [2, 39]] },
  9: { ecPerBlock: 22, blocks: [[3, 36], [2, 37]] },
  10: { ecPerBlock: 26, blocks: [[4, 43], [1, 44]] },
};

/**
 * Where the alignment patterns sit, as coordinates on both axes.
 *
 * Every pair of these is a pattern centre, minus the three corners the finders
 * already occupy. Version 1 has none, which is why the table starts at 2.
 */
const ALIGNMENT_CENTRES: Readonly<Record<number, readonly number[]>> = {
  1: [],
  2: [6, 18],
  3: [6, 22],
  4: [6, 26],
  5: [6, 30],
  6: [6, 34],
  7: [6, 22, 38],
  8: [6, 24, 42],
  9: [6, 26, 46],
  10: [6, 28, 50],
};

/** Level M's two bits in the format information. L is 1, M is 0, Q is 3, H is 2. */
const EC_LEVEL_M = 0;

/** Byte mode. The other three modes are not encoded here. */
const MODE_BYTE = 0b0100;

/* -------------------------------------------------------------------------- */
/* GF(256) — the arithmetic Reed-Solomon is done in                            */
/* -------------------------------------------------------------------------- */

/*
 * Multiplication in the field is addition of logarithms, so the two tables
 * below turn every product into a lookup. `EXP` is doubled in length so the
 * sum of two logarithms never has to be reduced modulo 255 at the call site.
 * The polynomial is 0x11D, which is the one the QR spec names.
 */
const EXP = new Uint8Array(512);
const LOG = new Uint8Array(256);

for (let i = 0, x = 1; i < 255; i += 1) {
  EXP[i] = x;
  LOG[x] = i;
  x <<= 1;
  if (x & 0x100) x ^= 0x11d;
}
for (let i = 255; i < 512; i += 1) EXP[i] = EXP[i - 255]!;

function multiply(a: number, b: number): number {
  // Zero has no logarithm, and it is the one case the tables cannot answer.
  if (a === 0 || b === 0) return 0;
  return EXP[LOG[a]! + LOG[b]!]!;
}

/**
 * The generator polynomial for `degree` error-correction codewords.
 *
 * (x - α⁰)(x - α¹)…, built up one root at a time. Coefficients run
 * highest-degree first, so `poly[0]` is always 1.
 */
function generatorPoly(degree: number): Uint8Array {
  let poly = new Uint8Array([1]);
  for (let root = 0; root < degree; root += 1) {
    const next = new Uint8Array(poly.length + 1);
    for (let i = 0; i < poly.length; i += 1) {
      next[i]! ^= poly[i]!;
      next[i + 1]! ^= multiply(poly[i]!, EXP[root]!);
    }
    poly = next;
  }
  return poly;
}

/** The remainder of the data block divided by the generator: its EC codewords. */
function errorCorrection(data: Uint8Array, count: number): Uint8Array {
  const generator = generatorPoly(count);
  const remainder = new Uint8Array(count);
  for (const byte of data) {
    const factor = byte ^ remainder[0]!;
    remainder.copyWithin(0, 1);
    remainder[count - 1] = 0;
    for (let i = 0; i < count; i += 1) {
      remainder[i]! ^= multiply(generator[i + 1]!, factor);
    }
  }
  return remainder;
}

/* -------------------------------------------------------------------------- */
/* The bitstream                                                               */
/* -------------------------------------------------------------------------- */

/** Total data codewords a version holds, across every block. */
function dataCodewords(version: number): number {
  return VERSIONS[version]!.blocks.reduce((total, [count, size]) => total + count * size, 0);
}

/**
 * How many bits the character count takes.
 *
 * Byte mode uses 8 bits up to version 9 and 16 from version 10 — the one place
 * where the header length depends on a version that has not been chosen yet,
 * which is why `pickVersion` below tries each version rather than dividing.
 */
function countBits(version: number): number {
  return version < 10 ? 8 : 16;
}

/** The smallest version that fits `length` bytes, or null if none does. */
function pickVersion(length: number): number | null {
  for (let version = 1; version <= MAX_VERSION; version += 1) {
    const capacity = dataCodewords(version) * 8 - 4 - countBits(version);
    if (length * 8 <= capacity) return version;
  }
  return null;
}

/**
 * Mode, length, the bytes themselves, and whatever padding the version needs.
 *
 * The two pad bytes alternate 0xEC / 0x11 as the spec requires. They are not
 * arbitrary: a run of zeroes would give the masking stage a large flat region
 * to score, and the alternating pair is what keeps an under-filled symbol
 * looking like data.
 */
function buildData(bytes: Uint8Array, version: number): Uint8Array {
  const total = dataCodewords(version);
  const out = new Uint8Array(total);
  let bit = 0;

  const write = (value: number, width: number) => {
    for (let i = width - 1; i >= 0; i -= 1) {
      if ((value >>> i) & 1) out[bit >>> 3]! |= 0x80 >>> (bit & 7);
      bit += 1;
    }
  };

  write(MODE_BYTE, 4);
  write(bytes.length, countBits(version));
  for (const byte of bytes) write(byte, 8);

  // The terminator is up to four zero bits, and short when the symbol is
  // nearly full — writing four into a symbol with two left is what the
  // "as many as will fit" clause exists to prevent.
  write(0, Math.min(4, total * 8 - bit));
  // Then to the byte boundary, so the pad bytes start where a codeword does.
  if (bit % 8 !== 0) write(0, 8 - (bit % 8));

  for (let i = bit >>> 3, pad = 0; i < total; i += 1, pad += 1) {
    out[i] = pad % 2 === 0 ? 0xec : 0x11;
  }
  return out;
}

/**
 * The final codeword sequence: data blocks interleaved, then EC blocks.
 *
 * Interleaving is what makes the symbol survive a thumb over one corner — a
 * contiguous smudge damages a few codewords of every block rather than every
 * codeword of one, and each block can then be repaired independently.
 */
function interleave(data: Uint8Array, version: number): Uint8Array {
  const spec = VERSIONS[version]!;
  const blocks: { data: Uint8Array; ec: Uint8Array }[] = [];

  let offset = 0;
  for (const [count, size] of spec.blocks) {
    for (let i = 0; i < count; i += 1) {
      const slice = data.subarray(offset, offset + size);
      offset += size;
      blocks.push({ data: slice, ec: errorCorrection(slice, spec.ecPerBlock) });
    }
  }

  const out: number[] = [];
  const longest = Math.max(...blocks.map((block) => block.data.length));
  for (let i = 0; i < longest; i += 1) {
    for (const block of blocks) if (i < block.data.length) out.push(block.data[i]!);
  }
  for (let i = 0; i < spec.ecPerBlock; i += 1) {
    for (const block of blocks) out.push(block.ec[i]!);
  }
  return new Uint8Array(out);
}

/* -------------------------------------------------------------------------- */
/* The symbol                                                                  */
/* -------------------------------------------------------------------------- */

/**
 * A drawn symbol, mid-construction.
 *
 * `reserved` marks every module the function patterns own — finders, timing,
 * alignment, the format and version areas. Two jobs: the data walk steps over
 * them, and the mask is applied to everything they do not cover, which is the
 * spec's rule and the reason it cannot simply XOR the whole grid.
 */
interface Grid {
  size: number;
  modules: boolean[][];
  reserved: boolean[][];
}

function blank(version: number): Grid {
  const size = version * 4 + 17;
  return {
    size,
    modules: Array.from({ length: size }, () => new Array<boolean>(size).fill(false)),
    reserved: Array.from({ length: size }, () => new Array<boolean>(size).fill(false)),
  };
}

function setFunction(symbol: Grid, row: number, col: number, dark: boolean): void {
  symbol.modules[row]![col] = dark;
  symbol.reserved[row]![col] = true;
}

/** The three 7×7 corners, with the light separator that has to surround them. */
function drawFinder(symbol: Grid, row: number, col: number): void {
  for (let dy = -1; dy <= 7; dy += 1) {
    for (let dx = -1; dx <= 7; dx += 1) {
      const y = row + dy;
      const x = col + dx;
      if (y < 0 || y >= symbol.size || x < 0 || x >= symbol.size) continue;
      const ring = Math.max(Math.abs(dy - 3), Math.abs(dx - 3));
      // Rings 0-2 are the solid centre and its light gap; 3 is the black
      // border; 4 is the separator, which is the whole reason this loop runs
      // one module wider than the pattern it draws.
      setFunction(symbol, y, x, ring !== 2 && ring !== 4);
    }
  }
}

function drawFunctionPatterns(symbol: Grid, version: number): void {
  drawFinder(symbol, 0, 0);
  drawFinder(symbol, 0, symbol.size - 7);
  drawFinder(symbol, symbol.size - 7, 0);

  // The two timing lines: alternating modules along row and column 6, which is
  // what a scanner counts to work out how wide one module is.
  for (let i = 8; i < symbol.size - 8; i += 1) {
    setFunction(symbol, 6, i, i % 2 === 0);
    setFunction(symbol, i, 6, i % 2 === 0);
  }

  const centres = ALIGNMENT_CENTRES[version]!;
  for (const row of centres) {
    for (const col of centres) {
      // The three corners belong to the finders; an alignment pattern there
      // would overwrite them.
      const corner =
        (row === 6 && col === 6) ||
        (row === 6 && col === symbol.size - 7) ||
        (row === symbol.size - 7 && col === 6);
      if (corner) continue;
      for (let dy = -2; dy <= 2; dy += 1) {
        for (let dx = -2; dx <= 2; dx += 1) {
          const ring = Math.max(Math.abs(dy), Math.abs(dx));
          setFunction(symbol, row + dy, col + dx, ring !== 1);
        }
      }
    }
  }

  // The module that is always dark, and the format areas around it. The format
  // bits themselves are written once a mask has been chosen; reserving them
  // now is what keeps the data walk out of them.
  setFunction(symbol, symbol.size - 8, 8, true);
  for (let i = 0; i < 9; i += 1) {
    if (!symbol.reserved[8]![i]) setFunction(symbol, 8, i, false);
    if (!symbol.reserved[i]![8]) setFunction(symbol, i, 8, false);
  }
  for (let i = 0; i < 8; i += 1) {
    if (!symbol.reserved[8]![symbol.size - 1 - i]) setFunction(symbol, 8, symbol.size - 1 - i, false);
    if (!symbol.reserved[symbol.size - 1 - i]![8]) setFunction(symbol, symbol.size - 1 - i, 8, false);
  }

  if (version >= 7) drawVersionInfo(symbol, version);
}

/**
 * The version number, twice, for symbols big enough to be ambiguous.
 *
 * Six bits and a twelve-bit BCH check, in two 3×6 blocks by the top-right and
 * bottom-left finders. Only from version 7, because below that a scanner can
 * count modules and be sure.
 */
function drawVersionInfo(symbol: Grid, version: number): void {
  let remainder = version;
  for (let i = 0; i < 12; i += 1) {
    remainder = (remainder << 1) ^ ((remainder >>> 11) * 0x1f25);
  }
  const bits = ((version << 12) | remainder) >>> 0;

  for (let i = 0; i < 18; i += 1) {
    const dark = ((bits >>> i) & 1) === 1;
    const near = symbol.size - 11 + (i % 3);
    const far = Math.floor(i / 3);
    setFunction(symbol, far, near, dark);
    setFunction(symbol, near, far, dark);
  }
}

/**
 * The error-correction level and the mask, twice over, with a BCH check.
 *
 * Duplicated on purpose by the spec: the format is the one thing a scanner
 * cannot read the symbol without, so it is written beside two different
 * finders and either copy will do.
 */
function drawFormatInfo(symbol: Grid, mask: number): void {
  const data = (EC_LEVEL_M << 3) | mask;
  let remainder = data;
  for (let i = 0; i < 10; i += 1) {
    remainder = (remainder << 1) ^ ((remainder >>> 9) * 0x537);
  }
  const bits = (((data << 10) | remainder) ^ 0x5412) >>> 0;
  const bit = (index: number) => ((bits >>> index) & 1) === 1;

  // The copy that runs down the left column and along the top row, around the
  // top-left finder…
  for (let i = 0; i <= 5; i += 1) setFunction(symbol, i, 8, bit(i));
  setFunction(symbol, 7, 8, bit(6));
  setFunction(symbol, 8, 8, bit(7));
  setFunction(symbol, 8, 7, bit(8));
  for (let i = 9; i <= 14; i += 1) setFunction(symbol, 8, 14 - i, bit(i));

  // …and the copy split between the other two, which is the one a scanner
  // falls back on when the top-left corner is the part under a thumb.
  for (let i = 0; i <= 7; i += 1) setFunction(symbol, 8, symbol.size - 1 - i, bit(i));
  for (let i = 8; i <= 14; i += 1) setFunction(symbol, symbol.size - 15 + i, 8, bit(i));
}

/**
 * The codewords, laid in the zigzag the spec describes.
 *
 * Two-module columns from the right edge leftwards, alternating up and down,
 * skipping column 6 — which is the vertical timing line and not a column of
 * data at all — and stepping over every reserved module on the way.
 */
function drawCodewords(symbol: Grid, codewords: Uint8Array): void {
  let bit = 0;
  for (let right = symbol.size - 1; right >= 1; right -= 2) {
    if (right === 6) right = 5;
    for (let vertical = 0; vertical < symbol.size; vertical += 1) {
      for (let column = 0; column < 2; column += 1) {
        const x = right - column;
        const upward = ((right + 1) & 2) === 0;
        const y = upward ? symbol.size - 1 - vertical : vertical;
        if (symbol.reserved[y]![x] || bit >= codewords.length * 8) continue;
        symbol.modules[y]![x] = ((codewords[bit >>> 3]! >>> (7 - (bit & 7))) & 1) === 1;
        bit += 1;
      }
    }
  }
}

/** The eight masks, as the spec's conditions. A true condition flips the module. */
const MASKS: readonly ((row: number, col: number) => boolean)[] = [
  (row, col) => (row + col) % 2 === 0,
  (row) => row % 2 === 0,
  (_row, col) => col % 3 === 0,
  (row, col) => (row + col) % 3 === 0,
  (row, col) => (Math.floor(row / 2) + Math.floor(col / 3)) % 2 === 0,
  (row, col) => ((row * col) % 2) + ((row * col) % 3) === 0,
  (row, col) => (((row * col) % 2) + ((row * col) % 3)) % 2 === 0,
  (row, col) => (((row + col) % 2) + ((row * col) % 3)) % 2 === 0,
];

/** XOR in place. Called twice per candidate — once to try it, once to undo it. */
function applyMask(symbol: Grid, mask: number): void {
  const condition = MASKS[mask]!;
  for (let row = 0; row < symbol.size; row += 1) {
    for (let col = 0; col < symbol.size; col += 1) {
      if (!symbol.reserved[row]![col] && condition(row, col)) {
        symbol.modules[row]![col] = !symbol.modules[row]![col];
      }
    }
  }
}

/*
 * The four penalty rules, and why a symbol is scored at all.
 *
 * A mask exists to stop the data drawing something that looks like a function
 * pattern or a large blank field, and the scoring is how the encoder picks the
 * least misleading of the eight. The weights are the spec's: runs of five cost
 * 3 and a point per extra module, every 2×2 block of one colour costs 3, a
 * finder-shaped run costs 40, and a symbol wildly off half-dark costs 10 per
 * 5% of imbalance.
 *
 * Encoders famously disagree here, and this one will not always pick the mask
 * another tool picks for the same payload: the spec leaves open whether the
 * format modules are on the grid while it is scored, and whether the quiet
 * zone counts as the light space a finder-shaped run needs beside it. Both
 * answers produce a symbol that scans — the mask is written into the format
 * information, so a scanner is told which one it is looking at — so nothing
 * downstream depends on the choice, and the tests do not pin it.
 */
const PENALTY_RUN = 3;
const PENALTY_BLOCK = 3;
const PENALTY_FINDER = 40;
const PENALTY_BALANCE = 10;

/**
 * How many finder-like 1:1:3:1:1 runs the last seven runs contain.
 *
 * Read from a rolling history rather than by matching an eleven-module string,
 * because the pattern the spec penalises is a *proportion* — dark:light:dark
 * in 1:1:3:1:1 — with four modules of light space on one side, and a run
 * history is the only form in which both directions are cheap to test.
 */
function finderPatterns(history: readonly number[]): number {
  const unit = history[1]!;
  const core =
    unit > 0 &&
    history[2] === unit &&
    history[3] === unit * 3 &&
    history[4] === unit &&
    history[5] === unit;
  if (!core) return 0;
  return (
    (history[0]! >= unit * 4 && history[6]! >= unit ? 1 : 0) +
    (history[6]! >= unit * 4 && history[0]! >= unit ? 1 : 0)
  );
}

/**
 * Pushes a finished run onto the history.
 *
 * The very first run of a line is lengthened by a whole symbol width, because
 * what sits before it is the quiet zone — unbounded light space — and a finder
 * pattern that starts at the left edge has to be able to score.
 */
function pushRun(history: number[], run: number, size: number): void {
  history.pop();
  history.unshift(history[0] === 0 ? run + size : run);
}

function penalty(symbol: Grid): number {
  const { size, modules } = symbol;
  let score = 0;

  const scoreLine = (at: (index: number) => boolean) => {
    const history = [0, 0, 0, 0, 0, 0, 0];
    let colour = false;
    let run = 0;
    for (let i = 0; i < size; i += 1) {
      if (at(i) === colour) {
        run += 1;
        if (run === 5) score += PENALTY_RUN;
        else if (run > 5) score += 1;
      } else {
        pushRun(history, run, size);
        if (!colour) score += finderPatterns(history) * PENALTY_FINDER;
        colour = at(i);
        run = 1;
      }
    }
    // Closing the line: the run in hand is finished, and the quiet zone past
    // the right edge is added to it if it is a light one — the mirror of the
    // border `pushRun` adds at the start.
    if (colour) {
      pushRun(history, run, size);
      run = 0;
    }
    pushRun(history, run + size, size);
    score += finderPatterns(history) * PENALTY_FINDER;
  };

  for (let row = 0; row < size; row += 1) scoreLine((col) => modules[row]![col]!);
  for (let col = 0; col < size; col += 1) scoreLine((row) => modules[row]![col]!);

  for (let row = 0; row < size - 1; row += 1) {
    for (let col = 0; col < size - 1; col += 1) {
      const value = modules[row]![col];
      if (
        value === modules[row]![col + 1] &&
        value === modules[row + 1]![col] &&
        value === modules[row + 1]![col + 1]
      ) {
        score += PENALTY_BLOCK;
      }
    }
  }

  let dark = 0;
  for (const row of modules) for (const module of row) if (module) dark += 1;
  const total = size * size;
  const off = Math.ceil(Math.abs(dark * 20 - total * 10) / total) - 1;
  return score + off * PENALTY_BALANCE;
}

/* -------------------------------------------------------------------------- */
/* The one thing this module exports                                           */
/* -------------------------------------------------------------------------- */

export interface QrCode {
  /** Modules a side. A version 4 symbol is 33. */
  size: number;
  /** The version chosen for the payload, 1 to 10. */
  version: number;
  /** Row-major and square: `modules[row][col]` is true where the square is dark. */
  modules: boolean[][];
}

/**
 * Encodes `text` as a QR symbol at error-correction level M.
 *
 * Level M rather than L because the thing being scanned is a phone screen held
 * at arm's length in a church foyer — glare and a fingerprint are the normal
 * case, and M's 15% recovery is what absorbs them. Not Q or H, which would
 * push the same URL into a denser symbol for the same camera.
 *
 * Throws for a payload no supported version holds. The caller is expected to
 * catch it and fall back to the link, which is the half of the journey that
 * always works.
 */
export function encodeQr(text: string): QrCode {
  const bytes = new TextEncoder().encode(text);
  const version = pickVersion(bytes.length);
  if (version === null) {
    throw new Error(`Too long for a QR code: ${bytes.length} bytes.`);
  }

  const symbol = blank(version);
  drawFunctionPatterns(symbol, version);
  drawCodewords(symbol, interleave(buildData(bytes, version), version));

  /*
   * Every mask is drawn, scored and undone, and the best-scoring one is drawn
   * again. Eight passes over a 33×33 grid is nothing next to the network round
   * trip that produced the token, and the alternative — picking a mask by rule
   * of thumb — is how a symbol ends up with a false finder in it.
   */
  let best = 0;
  let bestScore = Number.POSITIVE_INFINITY;
  for (let mask = 0; mask < 8; mask += 1) {
    applyMask(symbol, mask);
    drawFormatInfo(symbol, mask);
    const score = penalty(symbol);
    if (score < bestScore) {
      bestScore = score;
      best = mask;
    }
    applyMask(symbol, mask);
  }
  applyMask(symbol, best);
  drawFormatInfo(symbol, best);

  return { size: symbol.size, version, modules: symbol.modules };
}
