/**
 * Assembles the access walkthrough from what `e2e/access-walkthrough.spec.ts`
 * shot.
 *
 * Two outputs, the way every other walkthrough here has two: a Markdown file
 * the repository renders, and a standalone HTML page carrying every frame
 * inlined as a data URI — a published page cannot reach any external host, and
 * a walkthrough whose images 404 is worse than no walkthrough.
 *
 *   npm run walkthrough:access:build
 *
 * ## Both viewports, side by side
 *
 * Every screen this campaign touched has a phone story and a laptop story that
 * differ: the invite card is a disclosure on one and a column on the other, the
 * person page has to fit the 9:22 rescue into 390px, and the chip's dot has to
 * survive a tab bar underneath it. So each step carries both frames where both
 * exist, rather than picking one and letting the other rot unphotographed.
 *
 * JPEG at quality 72, like the main walkthrough: these are screenshots of flat
 * UI being read for layout and copy, not for colour — the theme walkthrough is
 * the one page where that trade is the wrong way round, and it says so.
 */
import { readFile, readdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

interface Shot {
  file: string;
  title: string;
  journey: string;
  caption: string;
  viewport: string;
}

interface Manifest {
  viewport: string;
  shots: Shot[];
}

const OUT = 'docs/uxr/access-walkthrough';

async function loadManifest(name: string): Promise<Shot[]> {
  try {
    const parsed = JSON.parse(await readFile(join(OUT, name), 'utf8')) as Manifest;
    return parsed.shots;
  } catch {
    return [];
  }
}

/**
 * The optimised frame if `walkthrough:optimize` has been over it, else the raw
 * capture. Running the build without the optimiser should produce a heavier
 * page, not a broken one.
 */
async function dataUri(file: string): Promise<string> {
  const jpg = file.replace(/\.png$/, '.jpg');
  try {
    const bytes = await readFile(join(OUT, 'web', jpg));
    return `data:image/jpeg;base64,${bytes.toString('base64')}`;
  } catch {
    const bytes = await readFile(join(OUT, 'shots', file));
    return `data:image/png;base64,${bytes.toString('base64')}`;
  }
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

const desktop = await loadManifest('desktop.json');
const phone = await loadManifest('phone.json');

if (desktop.length === 0 && phone.length === 0) {
  const captured = await readdir(OUT).catch(() => []);
  throw new Error(
    `No manifests in ${OUT} (found: ${captured.join(', ') || 'nothing'}). ` +
      'Run `npm run walkthrough:access:capture` first.',
  );
}

/**
 * Steps are matched by title, not by index.
 *
 * The two passes take the same route but do not always take the same number of
 * frames — a control that is behind a disclosure on a phone may be in the open
 * on a laptop, and a step that finds nothing to photograph is skipped rather
 * than faked. Matching on index would pair the wrong screens the first time
 * that happened, which is a page that lies about what a phone looks like.
 */
const order = desktop.length >= phone.length ? desktop : phone;
const byTitle = new Map<string, { desktop?: Shot; phone?: Shot }>();
for (const shot of desktop) byTitle.set(shot.title, { ...byTitle.get(shot.title), desktop: shot });
for (const shot of phone) byTitle.set(shot.title, { ...byTitle.get(shot.title), phone: shot });

const journeys: { name: string; steps: Shot[] }[] = [];
for (const step of order) {
  const last = journeys.at(-1);
  if (last?.name === step.journey) last.steps.push(step);
  else journeys.push({ name: step.journey, steps: [step] });
}

const LEAD =
  'Every screen here is the live app, signed in against the seeded emulator and photographed ' +
  'as the person it was designed for would meet it. The design it implements is ' +
  'docs/team-access.md, which converged over five rounds of critique and one review by the ' +
  'owner.';

/* -------------------------------------------------------------------------- */
/* Markdown                                                                    */
/* -------------------------------------------------------------------------- */

const markdown: string[] = [
  '# Team and access — a walkthrough',
  '',
  LEAD,
  '',
  '> Generated by `npm run walkthrough:access`. Do not edit by hand.',
  '',
];

for (const journey of journeys) {
  markdown.push(`## ${journey.name}`, '');
  for (const step of journey.steps) {
    const pair = byTitle.get(step.title)!;
    markdown.push(`### ${step.title}`, '', step.caption, '');
    if (pair.desktop) markdown.push(`![${step.title}](shots/${pair.desktop.file})`, '');
    if (pair.phone) markdown.push(`![${step.title}, on a phone](shots/${pair.phone.file})`, '');
  }
}

await writeFile(join(OUT, 'README.md'), `${markdown.join('\n')}\n`, 'utf8');

/* -------------------------------------------------------------------------- */
/* The page                                                                    */
/* -------------------------------------------------------------------------- */

const sections: string[] = [];
let stepNumber = 0;

for (const journey of journeys) {
  sections.push(
    `<section class="journey"><h2>${escapeHtml(journey.name)}</h2><div class="steps">`,
  );
  for (const step of journey.steps) {
    stepNumber += 1;
    const pair = byTitle.get(step.title)!;
    const desktopSrc = pair.desktop ? await dataUri(pair.desktop.file) : null;
    const phoneSrc = pair.phone ? await dataUri(pair.phone.file) : null;
    sections.push(`
    <article class="step">
      <header>
        <span class="num">${String(stepNumber).padStart(2, '0')}</span>
        <h3>${escapeHtml(step.title)}</h3>
      </header>
      <p>${escapeHtml(step.caption)}</p>
      <figure>
        ${desktopSrc ? `<img class="shot desktop" src="${desktopSrc}" alt="${escapeHtml(step.title)}" loading="lazy">` : ''}
        ${phoneSrc ? `<img class="shot phone" src="${phoneSrc}" alt="${escapeHtml(step.title)} on a phone" loading="lazy">` : ''}
      </figure>
    </article>`);
  }
  sections.push('</div></section>');
}

const html = `<title>Tally — team and access</title>
<style>
  :root {
    --paper: #f6f7f9;
    --raised: #ffffff;
    --ink: #12192a;
    --muted: #5a6579;
    --line: #dfe3ea;
    --accent: #0369a1;
    --shadow: 0 1px 2px rgb(18 25 42 / 8%), 0 12px 32px rgb(18 25 42 / 10%);
    --display: ui-serif, Georgia, 'Iowan Old Style', 'Times New Roman', serif;
    --body: ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif;
    --mono: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
  }
  @media (prefers-color-scheme: dark) {
    :root:not([data-theme='light']) {
      --paper: #0b1017; --raised: #131a24; --ink: #e7ecf3; --muted: #93a0b4;
      --line: #232c39; --accent: #56bdf3;
      --shadow: 0 1px 2px rgb(0 0 0 / 40%), 0 16px 40px rgb(0 0 0 / 45%);
    }
  }
  :root[data-theme='dark'] {
    --paper: #0b1017; --raised: #131a24; --ink: #e7ecf3; --muted: #93a0b4;
    --line: #232c39; --accent: #56bdf3;
    --shadow: 0 1px 2px rgb(0 0 0 / 40%), 0 16px 40px rgb(0 0 0 / 45%);
  }

  * { box-sizing: border-box; }
  body {
    margin: 0;
    background: var(--paper);
    color: var(--ink);
    font-family: var(--body);
    font-size: 17px;
    line-height: 1.6;
    -webkit-font-smoothing: antialiased;
  }
  .wrap { max-width: 72rem; margin: 0 auto; padding: 0 1.5rem 6rem; }

  header.masthead { max-width: 40rem; margin: 0 auto; padding: 4.5rem 0 3rem; }
  .eyebrow {
    font-family: var(--mono); font-size: 0.72rem; letter-spacing: 0.16em;
    text-transform: uppercase; color: var(--accent); margin: 0 0 1rem;
  }
  h1 {
    font-family: var(--display); font-size: clamp(2.2rem, 6vw, 3.4rem);
    line-height: 1.05; letter-spacing: -0.02em; font-weight: 600;
    margin: 0 0 1rem; text-wrap: balance;
  }
  .lead { color: var(--muted); margin: 0; text-wrap: pretty; }

  .journey { padding-top: 3.5rem; }
  .journey > h2 {
    font-family: var(--display); font-size: 1.6rem; font-weight: 600;
    margin: 0 0 1.5rem; padding-bottom: 0.75rem; border-bottom: 1px solid var(--line);
  }
  .steps { display: flex; flex-direction: column; gap: 3rem; }

  .step header { display: flex; align-items: baseline; gap: 0.75rem; }
  .num {
    font-family: var(--mono); font-size: 0.8rem; color: var(--accent);
    letter-spacing: 0.08em;
  }
  .step h3 { font-size: 1.15rem; font-weight: 650; margin: 0; }
  .step p { color: var(--muted); margin: 0.35rem 0 1rem; max-width: 46rem; text-wrap: pretty; }

  figure {
    margin: 0; display: grid; gap: 1.25rem;
    grid-template-columns: 1fr;
    align-items: start;
  }
  @media (min-width: 60rem) { figure:has(.phone):has(.desktop) { grid-template-columns: 1fr 22rem; } }
  .shot {
    display: block; width: 100%; height: auto; max-width: 100%;
    border-radius: 14px; border: 1px solid var(--line); box-shadow: var(--shadow);
  }

  footer { padding-top: 4rem; color: var(--muted); font-size: 0.9rem; }
</style>
<div class="wrap">
  <header class="masthead">
    <p class="eyebrow">Tally</p>
    <h1>Team and access</h1>
    <p class="lead">${escapeHtml(LEAD)}</p>
  </header>
  ${sections.join('\n')}
  <footer>Generated by <code>npm run walkthrough:access</code>.</footer>
</div>
`;

await writeFile(join(OUT, 'access-walkthrough.html'), html, 'utf8');

console.log(
  `Wrote ${OUT}/access-walkthrough.html and README.md — ${stepNumber} step(s), ` +
    `${desktop.length} desktop and ${phone.length} phone frame(s).`,
);
